name: Rust

on:
  pull_request:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Transmission
      run: sudo apt-get -y install transmission-cli

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose
